version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - ./grafana:/etc/grafana/provisioning

  stats_db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: stats
      MYSQL_USER: stats
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

  redis:
    image: redis:alpine
  # celery:
  #   build: ./nodewatcher
  #   command: celery -A core worker -l info
  #   volumes:
  #     - ./nodewatcher/:/usr/src/app/
  #   environment:
  #     - BLOCKFROST_KEY=SET_ME
  #   depends_on:
  #     - redis
  # celery-beat:
  #   build: ./nodewatcher
  #   command: celery -A core beat -l info
  #   volumes:
  #     - ./nodewatcher/:/usr/src/app/
  #   depends_on:
  #     - redis
