version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - ./grafana:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - /var/tmp/prometheus/data:/prometheus
    ports:
      - 9090:9090

  blackbox:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:latest
    volumes:
      - ./blackbox-exporter:/config
    ports:
      - 9115:9115

  nodewatcher:
    container_name: nodewatcher
    build: ./nodewatcher
    command: flask run --host=0.0.0.0 --debug
    volumes:
      - ./nodewatcher:/nodewatcher
    working_dir: /nodewatcher
    ports:
      - 5000:5000
