{
 "title": "Node Watcher",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ticker", "label": "Pool Ticker", "query": { "query": "label_values(ticker)" } }
  ]
 },
 "panels": [
  {
   "title": "Cardano Nodes Online",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=\"blackbox-tcp\"} == 1)"
    }
   ]
  },
  {
   "title": "Cardano Nodes Offline",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=\"blackbox-tcp\"} == 0)"
    }
   ]
  },
  {
   "title": "Percentage of Public Nodes Online",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=\"blackbox-tcp\"}==1)/count(probe_success{job=\"blackbox-tcp\"})*100"
    }
   ]
  },
  {
   "title": "Insecure SSH Port",
   "type": "stat",
   "description": "SSH banners being displayed on an open TCP port 22 is not really a great idea.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=\"insecure_ssh\"} == 1)"
    }
   ]
  },
  {
   "title": "Insecure SSH Ports",
   "type": "table",
   "description": "These nodes have their SSH ports open to the world, or at least wherever you are monitoring this from.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance, bech, ticker) (probe_success{job=\"insecure_ssh\", ticker=~\"$ticker\"}) == 1"
    }
   ]
  },
  {
   "title": "Offline Nodes",
   "type": "table",
   "description": "The nodes listed here are not responding to TCP connections on their on-chain registered address.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance, bech, ticker) (probe_success{job=\"blackbox-tcp\", ticker=~\"$ticker\"}) == 0"
    }
   ]
  }
 ]
}